var HostMap = {
	'Advertisements': /(^.*\?file=ads&.*$)|(^https?:\/\/([^\/]+\.)?(adsafeprotected|bkrtx)\.com\/.*$)|(^.*\/recommendations\/ad\..*$)|(^.*\/smartbanner\/.*$)|(^https?:\/\/([^\/]+\.)?ads\.[^\.]+\..*\/.*$)|(^.*:\/\/ads\..*$)|(^.*_(160x600|728x90|320x250)_?\..*$)|(^.*(160x600|728x90)\.html?.*$)|(^.*=300x250&.*$)/,
	'Tracking': /^(https?:\/\/([^\/]+\.)?a\.wikia-beacon\.com\/.*)|(.*\/analytics\/js\/.*)$/,

	'Google Tracking': /^(.*\/google-analytics-.*)|(https?:\/\/([^\/]+\.)?(google-analytics|googletagservices)\.com\/.*)$/,
	'Twitter': ['platform.twitter.com', 'www.twitter.com'],
	'Reddit': ['www.reddit.com'],
	'Facebook': /^https?:\/\/([^\/]+\.)?facebook\.(com|net)\/.*$/,
	'Chartbeat Tracking': ['static.chartbeat.com'],
	'Google+': /(^https?:\/\/apis\.google\.com\/js\/plusone\.js$)|(^.*\/googleplus\..*$)/,
	'Google Advertisements': ['partner.googleadservices.com', 'www.googleadservices.com', 'pagead2.googlesyndication.com', 'stats.g.doubleclick.net', 'survey.g.doubleclick.net', 'stats.doubleclick.net', 'doubleclick.net', 'ad.doubleclick.net'],
	'IntelliTXT Advertisements': /^https?:\/\/([^\/]+\.)?intellitxt\.com\/intellitxt\/.*$/,
	'Scorecard Research Tracking': ['a.scorecardresearch.com', 'b.scorecardresearch.com'],
	'CPMStar Advertisements': ['server.cpmstar.com', 'cpmstar.com'],
	'Gorilla Nation Advertisements': ['cdn.triggertag.gorillanation.com'],
	'Quantserve Tracking and Ads': /^(.*\/quant\.js.*$)|(https?:\/\/(edge|secure|pixel)\.quantserve\.com\/.*)$/,
	'Krux Tracking': ['cdn.krxd.net'],
	'PubGears Advertisements': ['tags.pubgears.com'],
	'OpenX Advertisements': /^.*\.openx\..*$/,
	'Lotame Advertisements': ['tags.crwdcntrl.net', 'ad.crwdcntrl.net'],
	'Marketo Tracking': ['munchkin.marketo.net'],
	'Qualaroo Tracking': /(^https?:\/\/([^\/]+\.)?amazonaws\.com\/ki\.js\/.*$)/,
	'Liji Tracking and Ads': /^https?:\/\/([^\/]+\.)?lijit\.com\/delivery\/.*$/,
	'Amazon Advertisements': /(^https?:\/\/([^\/]+\.)?amazon-adsystem\.com([^a-zA-Z0-9_\.%-]+|$).*$)|(^https?:\/\/([^\/]+\.)?amazon\.com\/aan\/.*$)|(^https?:\/\/([^\/]+\.)?amazon\.com([^a-zA-Z0-9_\.%-]+|$).*\/getaanad\?.*$)/,
	'ValueClick Advertisements': ['media.fastclick.net'],
	'Contextly Recommendations': /^https?:\/\/([^\/]+\.)?contextly\.com([^a-zA-Z0-9_\.%-]+|$).*$/,
	'Pingdom Website Monitoring': ['rum-static.pingdom.net'],
	'GoTraffic Advertisements': ['cdn.gotraffic.net'],
	'Perfect Market Tracking': ['widget.perfectmarket.com'],
	'Truste Tracking': /^https?:\/\/([^\/]+\.)?truste\.com\/notice\?.*consent-track.*$/,
	'Newstogram Recommendations': ['static.newstogram.com'],
	'Quintelligence Tracking': ['log2.quintelligence.com', 'log1.quintelligence.com', 'quintelligence.com'],
	'New Relic Website Monitoring': ['js-agent.newrelic.com'],
	'Skimlinks Tracking': /^https?:\/\/([^\/]+\.)?(skimresources|skimlinks)\.com\/.*$/,
	'Parsely Tracking': ['static.parsely.com'],
	'Pinterest': ['assets.pinterest.com'],
	'Optimizely Tracking': ['cdn.optimizely.com'],
	'ADTECH Advertisements': ['adserver.adtech.com'],
	'MotherJones Tracking': /^https?:\/\/([^\/]+\.)?amazonaws\.com\/ansible\.js.*$/,
	'Ensighten Tracking': ['nexus.ensighten.com'],
	'Media.net Advertisements': ['contextual.media.net'],
	'LinkSmart Tracking': ['cdn.linksmart.com'],
	'Tynt Clipboard Modifier': /^https?:\/\/([^\/]+\.)?tynt\.com\/.*$/,
	'Bounce Exchange Tracking': ['bounceexchange.com'],
	'IndustryBrains Advertisements': /^https?:\/\/([^\/]+\.)?industrybrains\.com([^a-zA-Z0-9_\.%-]+|$).*$/,
	'Dynamic Logic Advertisements': ['content.dl-rms.com'],
	'AddThis Social': /^https?:\/\/([^\/]+\.)?addthis\.com\/.*$/,
	'ShareThis Social': /^https?:\/\/([^\/]+\.)?sharethis\.com\/.*$/,
	'Tumblr': ['platform.tumblr.com'],
	'Sharethrough Advertisements': ['apis.sharethrough.com', 'native.sharethrough.com'],
	'Bizographics Advertisements': /^https?:\/\/([^\/]+\.)?bizographics\.com\/.*$/,
	'AdRoll Advertisements': /^https?:\/\/([^\/]+\.)?adroll\.com\/.*$/,
	'Compete Tracking': /^https?:\/\/([^\/]+\.)?compete\.com\/.*$/,
	'MaxMind Tracking': /^https?:\/\/([^\/]+\.)?maxmind\.com\/.*$/,
	'Peer39 Advertisements': ['stags.peer39.net'],
	'AdSpeed Advertisements': /^https?:\/\/([^\/]+\.)?adspeed\.net\/.*$/,
	'Effective Measure Advertisements': ['me-cdn.effectivemeasure.net'],
	'PubMatic Advertisements': ['Adspubmatic.com'],
	'Moat Ad Advertisements': /^https?:\/\/([^\/]+\.)?moatads\.com\/.*$/,
	'InsightExpress Tracking': /^https?:\/\/([^\/]+\.)?insightexpressai\.com\/.*$/,
	'LimeLightNetworks Ads': /^https?:\/\/([^\/]+\.)?llnwd\.net\/.*$/,
	'LinkedIn': ['platform.linkedin.com'],
	'nRelate Recommendations': ['api.nrelate.com'],
	'Wordpress Tracking': /^https?:\/\/([^\/]+\.)?stats\.wordpress\.com\/.*$/,
	'Criteo Advertisements': /^https?:\/\/([^\/]+\.)?criteo\.com\/.*$/,
	'Visual Revenue Tracking': /^https?:\/\/([^\/]+\.)?visualrevenue\.com\/.*$/,
	'Newsinc Tracking': /^https?:\/\/([^\/]+\.)?newsinc\.com\/.*$/,
	'YieldMo Advertisements': ['static.yieldmo.com'],
	'StumbleUpon': ['www.stumbleupon.com'],
	'Simplifi Advertisements': /^https?:\/\/([^\/]+\.)?simpli\.fi\/.*$/,
	'Project Wonderful Ads': ['www.projectwonderful.com'],
	'Adzerk Advertisements': ['static.adzerk.net'],
	'Fonts.com Tracking': /^https?:\/\/([^\/]+\.)?fonts\.com\/t\/trackingCode\.js.*$/,
	'ru4 Advertisements': /^https?:\/\/([^\/]+\.)?ru4\.com\/.*$/,
	'Adobe Tracking': /^https?:\/\/([^\/]+\.)?omtrdc\.net([^a-zA-Z0-9_\.%-]+|$).*$/,
	'Federated Media Ads': ['static.fmpub.net'],
	'BuySellAds Advertisements': /^https?:\/\/([^\/]+\.)?buysellads\.com\/.*$/,
	'RadiumOne Advertisements': /^https?:\/\/([^\/]+\.)?gwallet\.com\/.*$/,
	'ZDTag Tracking': /^https?:\/\/([^\/]+\.)?zdtag\.com\/.*$/,
	'PriceGrabber': /^https?:\/\/([^\/]+\.)?pricegrabber\.com\/cb_table\.php.*$/,
	'Evidon Tracking': /^https?:\/\/([^\/]+\.)?betrad\.com\/.*$/,
	'StatCounter Tracking': /^https?:\/\/([^\/]+\.)?statcounter\.com\/.*$/,
	'AdExcite Advertisements': /^https?:\/\/([^\/]+\.)?adexcite\.com\/.*$/,
	'NetShelter Advertisements': /^https?:\/\/([^\/]+\.)?netshelter\.net\/.*$/,
	'Monetate Tracking': /^https?:\/\/([^\/]+\.)?monetate\.net\/.*$/,
	'Foresee Tracking': /^.*\/foresee\/.*$/,
	'WebTrends Tracking': /^.*\/wt(base|init)\.js.*$/,
	'24/7 RealMedia Advertisements': /^(https?:\/\/([^\/]+\.)?247realmedia\.com\/.*)|(.*\/adstream_.*)|(.*\/realmedia\/ads\/.*)$/,
	'OwnerIQ Tracking': /^https?:\/\/([^\/]+\.)?owneriq\.net\/.*$/,
	'MIG Advertisements': /^https?:\/\/([^\/]+\.)?mookie1\.com\/.*$/,
};